Allow zipping directories greater than 4GB and creation of of ZIP files greater than 4GB
A customer has complained that despite their app. version being 300MB in size,
they are seeing the following error message during eb deploy:

	ERROR: LargeZipFile - Files count would require ZIP64 extensions

The exception is raised in the CPython zipfile.py module when a zip file OR
its uncompressed form exceeds 4 GB. We can overcome this problem by instantiating
ZipFile class with allowZip64=True explicitly.

It is likely that the customer is using Python 2.7.x, because Python 3.6, 3.5,
and 3.4 default to setting allowZip64 to True. To immediately remedy the problem,
the customer could switch to using Python 3.4, 3.5, or 3.6.

SIM: https://sim.amazon.com/issues/BEANSTALK-15963

cr https://code.amazon.com/reviews/CR-2386180