Fall back to unicode getwch for Python 3 on Win
Not doing so causes this error:
    File "C:\Python34\lib\site-packages\ebcli\health\screen.py", line 121, in handle_input
        char = str(val).upper()
        TypeError: __str__ returned non-string (type bytes)

Also bump to 3.5rc5 for testing.

cr https://cr.amazon.com/r/4063802/